# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  install_all_flutter_pods(flutter_application_path)

  pod 'SDWebImage'

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
